default: &default
  adapter: postgresql
  # encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME") { 'fuzzy_tutor' } %>    # Changed to use "DB_NAME" instead of "DB_Name"
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'Test123' } %>

development:
  <<: *default
  database: fuzzy_tutor

test:
  <<: *default
  database: fuzzy_tutor_test

production:
  <<: *default
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  database: <%= ENV.fetch("DB_NAME") { 'verceldb' } %>   # Changed to use "DB_NAME" instead of "DB_Name"
  host: <%= ENV.fetch("DB_HOST") { 'ep-lively-cloud-90069927-pooler.us-east-1.postgres.vercel-storage.com' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'default' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'TGU8AymfLv3e' } %>
  encoding: utf8
